"""Тесты PostgreSQL-бэкенда БД: _translate_pg, _PgAdapter, Database с DSN.

Не требуют живого PostgreSQL: asyncpg мокается. Проверяем:
  * _translate_pg — placeholder ?→$N, datetime('now')→now(), AUTOINCREMENT,
    INSERT OR REPLACE/IGNORE → ON CONFLICT DO NOTHING, PRAGMA/VACUUM → no-op;
  * _PgAdapter.execute — SELECT → ленивый курсор, DML → немедленный, no-op;
  * Database(path=postgres://...) — is_postgres=True, connect через asyncpg,
    SQLite-специфичные шаги (бэкап/vacuum/права) пропускаются.
"""

import asyncio
import sys
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.database import Database, _PgAdapter, _PgCursor, _translate_pg

PG_DSN = "postgres://user:pass@localhost:5432/harvest"


def _run(coro):
    loop = asyncio.new_event_loop()
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


class TestTranslatePg(unittest.TestCase):
    def test_placeholder_sequential(self):
        sql, params = _translate_pg("SELECT * FROM t WHERE a = ? AND b = ?", (1, 2))
        self.assertEqual(sql, "SELECT * FROM t WHERE a = $1 AND b = $2")
        self.assertEqual(params, (1, 2))

    def test_datetime_now(self):
        sql, _ = _translate_pg("UPDATE t SET ts = datetime('now') WHERE id = ?", (1,))
        self.assertIn("now()", sql)
        self.assertNotIn("datetime", sql)

    def test_autoincrement(self):
        sql, _ = _translate_pg(
            "CREATE TABLE x (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)"
        )
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", sql)
        self.assertNotIn("AUTOINCREMENT", sql)

    def test_insert_or_replace(self):
        sql, params = _translate_pg(
            "INSERT OR REPLACE INTO nonces (address, current_nonce) VALUES (?, ?)", ("a", 1)
        )
        self.assertIn("INSERT INTO nonces", sql)
        self.assertIn("ON CONFLICT DO NOTHING", sql)
        self.assertIn("$1", sql)

    def test_insert_or_ignore(self):
        sql, _ = _translate_pg(
            "INSERT OR IGNORE INTO wallet_group_map (address, group_id) VALUES (?, ?)", ("a", 1)
        )
        self.assertIn("INSERT INTO wallet_group_map", sql)
        self.assertIn("ON CONFLICT DO NOTHING", sql)

    def test_upsert_already_has_on_conflict(self):
        sql, _ = _translate_pg(
            "INSERT INTO wallets (address) VALUES (?) ON CONFLICT(address) DO UPDATE SET x = 1",
            ("a",),
        )
        self.assertEqual(sql.count("ON CONFLICT"), 1)

    def test_pragma_noop(self):
        sql, _ = _translate_pg("PRAGMA wal_checkpoint(TRUNCATE)")
        self.assertTrue(sql.startswith("--"))

    def test_vacuum_noop(self):
        sql, _ = _translate_pg("VACUUM")
        self.assertTrue(sql.startswith("--"))

    def test_plain_select_unchanged_params(self):
        sql, params = _translate_pg("SELECT address FROM wallets ORDER BY address LIMIT ?", (5,))
        self.assertIn("$1", sql)
        self.assertEqual(params, (5,))


class _FakeConn:
    """Имитация asyncpg-соединения."""

    def __init__(self):
        self.executed = []
        self.fetched = []
        self.closed = False

    async def execute(self, sql, *params):
        self.executed.append((sql, params))
        return "OK"

    async def fetch(self, sql, *params):
        self.fetched.append((sql, params))
        if "cycle_history" in sql:
            return [("rpc_calls",), ("rpc_errors",), ("rpc_latency_ms",)]
        return []

    async def executemany(self, sql, args):
        self.executed.append((sql, tuple(args)))

    async def close(self):
        self.closed = True


class TestPgAdapter(unittest.TestCase):
    def test_select_lazy_cursor(self):
        conn = _FakeConn()
        adapter = _PgAdapter(conn)
        cur = adapter.execute("SELECT address FROM wallets", ())
        self.assertIsInstance(cur, _PgCursor)
        rows = _run(cur.fetchall())
        self.assertEqual(rows, [])
        self.assertEqual(len(conn.fetched), 1)

    def test_dml_immediate(self):
        conn = _FakeConn()
        adapter = _PgAdapter(conn)
        cur = adapter.execute("INSERT INTO wallets (address) VALUES ($1)", ("a",))
        _run(cur)  # await курсора выполняет DML
        self.assertEqual(len(conn.executed), 1)

    def test_noop_execute(self):
        conn = _FakeConn()
        adapter = _PgAdapter(conn)
        cur = adapter.execute("PRAGMA wal_checkpoint(TRUNCATE)", ())
        rows = _run(cur.fetchall())
        self.assertEqual(rows, [])
        self.assertEqual(conn.executed, [])

    def test_executemany(self):
        conn = _FakeConn()
        adapter = _PgAdapter(conn)
        _run(adapter.executemany("INSERT OR IGNORE INTO m (a) VALUES (?)", [("x",), ("y",)]))
        self.assertEqual(len(conn.executed), 1)
        self.assertIn("ON CONFLICT DO NOTHING", conn.executed[0][0])

    def test_executemany_empty(self):
        conn = _FakeConn()
        adapter = _PgAdapter(conn)
        _run(adapter.executemany("INSERT INTO m (a) VALUES (?)", []))
        self.assertEqual(conn.executed, [])

    def test_executescript(self):
        conn = _FakeConn()
        adapter = _PgAdapter(conn)
        _run(adapter.executescript("CREATE TABLE x (id INT); CREATE INDEX i ON x(id);"))
        # 2 DDL -> 2 executed
        self.assertGreaterEqual(len(conn.executed), 1)

    def test_commit_and_close(self):
        conn = _FakeConn()
        adapter = _PgAdapter(conn)
        _run(adapter.commit())
        _run(adapter.close())
        self.assertTrue(conn.closed)
        _run(adapter.close())  # идемпотентно


class TestDatabasePostgres(unittest.TestCase):
    def test_is_postgres_detected(self):
        self.assertTrue(Database(PG_DSN).is_postgres)
        self.assertTrue(Database("postgresql://u:p@h/db").is_postgres)
        self.assertFalse(Database("farming_state.db").is_postgres)
        self.assertFalse(Database(":memory:").is_postgres)

    def test_connect_uses_asyncpg(self):
        db = Database(PG_DSN)
        fake = _FakeConn()
        with mock.patch("asyncpg.connect", new=mock.AsyncMock(return_value=fake)):
            conn = _run(db._connect())
        self.assertIsInstance(conn, _PgAdapter)
        _run(db.close())

    def test_init_skips_sqlite_file_steps(self):
        db = Database(PG_DSN)
        fake = _FakeConn()
        # fetch для information_schema вернёт [("rpc_calls",),...] → миграции не нужны
        with mock.patch("asyncpg.connect", new=mock.AsyncMock(return_value=fake)):
            with mock.patch.object(db, "_migrate_legacy_seeds", new=mock.AsyncMock(return_value=False)):
                _run(db.init())
        # Никаких файловых шагов (бэкап/vacuum/права) не вызывалось
        self.assertFalse(hasattr(db, "_backup_dir_called"))
        _run(db.close())

    def test_backup_now_none_for_pg(self):
        db = Database(PG_DSN)
        result = _run(db.backup_now())
        self.assertIsNone(result)

    def test_list_backups_empty_for_pg(self):
        db = Database(PG_DSN)
        self.assertEqual(db.list_backups(), [])

    def test_cursor_fetchone_returns_none_when_empty(self):
        conn = _FakeConn()
        cur = _PgCursor(conn, "SELECT 1 WHERE false", ())
        self.assertIsNone(_run(cur.fetchone()))

    def test_cursor_context_manager(self):
        conn = _FakeConn()
        cur = _PgCursor(conn, "SELECT address FROM wallets", ())
        _run(cur.__aenter__())
        rows = _run(cur.fetchall())
        self.assertEqual(rows, [])
        _run(cur.__aexit__())


if __name__ == "__main__":
    unittest.main()
